# Generated by Django 2.0.5 on 2019-01-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_code', models.CharField(max_length=255)),
                ('to_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='exchangerates',
            unique_together={('from_code', 'to_code')},
        ),
    ]
