# Generated by Django 2.0.5 on 2019-01-23 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExchangeRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('date', models.DateField()),
                ('exchange_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange_rate.ExchangeRates')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dailyexchangerates',
            unique_together={('date', 'exchange_rate')},
        ),
    ]
