version: "3.5"

services:
  postgres:
    build:
      context: ./services/db
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    ports:
      - "5432:${POSTGRES_DB_PORT}"
    restart: always

  server:
    build:
      context: ./services/server
    ports:
      - "8000:${DJANGO_SERVER_PORT}"
    environment:
      POSTGRES_HOST: ${POSTGRES_DB_HOST}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_DB_PORT}
      POSTGRES_NAME: ${POSTGRES_DB_NAME}
    depends_on:
      - postgres
    restart: always
