version: "3.5"

services:
  postgres:
    build:
      context: ./services/db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:${POSTGRES_PORT}"
    restart: always

  server:
    build:
      context: ./services/server
    ports:
      - "8000:${DJANGO_SERVER_PORT}"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on:
      - postgres
    restart: always
